export const SET_FIELD_VALUE='SET_FIELD_VALUE';
export const CHECKED_TYPES='CHECKED_TYPES';
export const SET_TYPES='SET_TYPES';
export const SET_ALL_ITEMS='SET_ALL_ITEMS';
export const SET_ITEM='SET_ITEM';
export const SET_FIELDS_ITEM='SET_FIELDS_ITEM';